name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to ECS
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -f docker/Dockerfile.prod -t ${{ secrets.ECR_IMAGE_URI }} .
          docker push ${{ secrets.ECR_IMAGE_URI }}

      - name: Replace image URI in task definition
        run: |
          sed "s|REPLACE_ME_IMAGE_URI|${{ secrets.ECR_IMAGE_URI }}|" ecs/task-def.json > ecs/task-def.rendered.json

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task-def.rendered.json
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true